### ISSUE TITLE
Depósito de trabajos en el GitHUB

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/impresion3d#5]
![](https://octodex.github.com/images/jenktocat.jpg)

Muchos conocen a Github por ser la red social de los desarrolladores, para ser más específicos, podríamos decir que Github, bien puede ser la Wikipedia de la programación. En Github puedes buscar, ver, editar y copiar cientos de miles de proyectos de Open Source, en un mundo donde el 70% de las empresas de software hacen Open Source, es clave tener un lugar en donde podamos buscar dichos proyectos, Github es eso.

**Comment by IoTeacher** [comment]
Estimados colegas, favor de registrarse en GitHub trae dos bondades, una es dejar la huella digital de portafolio electrónico que nos solicita Coordinación.

Otro es que trae un visualizador de .STL archivos para presentar en modo borrador.

Y claro con este me enlazo para retraer el archivo y mandarlo imprimir al pasillo del laboratorio.

**Comment by mrsranzart** [comment]
Intenté subir el archivo .STL y no me deja :(

**Comment by IoTeacher** [comment]
Pasos genericos de registro en GitHUB

1. Acceder a http://github.com
2. Registrarse, procure usar combinación de su nombre real (despues lo puede cambiar)
![](http://res.cloudinary.com/codigofacilito/image/upload/v1439846486/Screen_Shot_2015-08-17_at_16.20.17_jpokqf.png)
3. Validar su correo la bienvenida.
4. Solicitar a Rene Solis, lo asigne como administrador de REPO y tenga permiso de subir archivos
5. Subir su archivo si es borrador a PRACTICAS y si es para imprimir  PROYECTOS
![upload](https://user-images.githubusercontent.com/2523851/27159279-a88ffb44-5120-11e7-8e6f-817fe17f8f2d.PNG)
