### ISSUE TITLE
Archivo de fotografias

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/impresion3d#8]
# FOTOS DE EVIDENCIAS DEL CURSO,  y PANTALLAZOS SON BIENVENIDOS. 
## Att. Coordinación

**Comment by IoTeacher** [comment]
![img_7316](https://user-images.githubusercontent.com/2523851/27206710-0debdec2-51ee-11e7-9006-386453146e2e.JPG)

**Comment by IoTeacher** [comment]
![img_7309](https://user-images.githubusercontent.com/2523851/27206726-1c812604-51ee-11e7-9ee9-7f24636d3c70.JPG)
![img_7310](https://user-images.githubusercontent.com/2523851/27206730-1c93bb66-51ee-11e7-96ef-d388b8f57787.JPG)
![img_7311](https://user-images.githubusercontent.com/2523851/27206731-1c98168e-51ee-11e7-897b-f0fea2f00e0e.JPG)
![img_7312](https://user-images.githubusercontent.com/2523851/27206728-1c85ef86-51ee-11e7-8ed5-5fe199fc748f.JPG)
![img_7313](https://user-images.githubusercontent.com/2523851/27206729-1c8731c0-51ee-11e7-9d7a-18cbd043821b.JPG)
![img_7314](https://user-images.githubusercontent.com/2523851/27206727-1c8336ba-51ee-11e7-906f-f319db7f0dce.JPG)
![img_7315](https://user-images.githubusercontent.com/2523851/27206736-1cb0d1e2-51ee-11e7-998e-1ac6ca0b4ad3.JPG)
![img_7317](https://user-images.githubusercontent.com/2523851/27206734-1caccc8c-51ee-11e7-89ec-c24f08e1c92b.JPG)
![img_7318](https://user-images.githubusercontent.com/2523851/27206732-1c9c85fc-51ee-11e7-8923-c4b597c35a94.JPG)
![img_7319](https://user-images.githubusercontent.com/2523851/27206733-1ca2d4b6-51ee-11e7-8077-be8cda8a7a45.JPG)
![img_7344](https://user-images.githubusercontent.com/2523851/27206735-1cae3572-51ee-11e7-8369-1a494b7f9546.JPG)
![img_7345](https://user-images.githubusercontent.com/2523851/27206738-1cb3a1a6-51ee-11e7-8b22-03a8c2dda724.JPG)
![img_7347](https://user-images.githubusercontent.com/2523851/27206737-1cb3a64c-51ee-11e7-82e9-76c1a5381f2b.JPG)
![img_7348](https://user-images.githubusercontent.com/2523851/27206739-1cbb6e04-51ee-11e7-8b62-1f5fc0d0679a.JPG)

**Comment by IoTeacher** [comment]
# Maestro Ray con su Spiner
![spinerray](https://user-images.githubusercontent.com/2523851/27208404-4f9f2796-51fa-11e7-9c20-00e6c3c3e0f8.JPG)

**Comment by adolfomedina** [comment]
![dsc_0431](https://user-images.githubusercontent.com/29418015/27244822-37134be6-529d-11e7-974d-545dc0a108ae.JPG)
![dsc_0432](https://user-images.githubusercontent.com/29418015/27244821-37127356-529d-11e7-8c33-b6c1f5253f31.JPG)
![dsc_0433](https://user-images.githubusercontent.com/29418015/27244819-3710305a-529d-11e7-8856-eb3073c6f904.JPG)
![dsc_0434](https://user-images.githubusercontent.com/29418015/27244824-3725f728-529d-11e7-92dc-6d95da6e5c0c.JPG)
![dsc_0435](https://user-images.githubusercontent.com/29418015/27244820-3711c3f2-529d-11e7-96e2-361b23823d08.JPG)
![dsc_0436](https://user-images.githubusercontent.com/29418015/27244823-37255aa2-529d-11e7-9960-88670dce024a.JPG)
![dsc_0437](https://user-images.githubusercontent.com/29418015/27244829-373a91ec-529d-11e7-8c11-035e9ab3ade4.JPG)
![dsc_0439](https://user-images.githubusercontent.com/29418015/27244827-3738a922-529d-11e7-9e08-5bed2a795253.JPG)
![dsc_0440](https://user-images.githubusercontent.com/29418015/27244825-3729b5a2-529d-11e7-9c77-f543a43ce708.JPG)
![dsc_0441](https://user-images.githubusercontent.com/29418015/27244826-372ad388-529d-11e7-901f-57fe7d382460.JPG)
![dsc_0442](https://user-images.githubusercontent.com/29418015/27244830-373f8166-529d-11e7-9628-7b25dda69449.JPG)
![dsc_0444](https://user-images.githubusercontent.com/29418015/27244831-3740a2ee-529d-11e7-9ba6-9296140bd64f.JPG)
![dsc_0445](https://user-images.githubusercontent.com/29418015/27244832-37414b18-529d-11e7-81d8-cdbb1c567304.JPG)
![dsc_0446](https://user-images.githubusercontent.com/29418015/27244833-37430d2c-529d-11e7-8f2a-1be4223fdc94.JPG)

**Comment by adolfomedina** [comment]
Escaneando una Cabeza y mas

**Comment by IoTeacher** [comment]
# FOTOS DE EVIDENCIAS DEL CURSO,  y PANTALLAZOS SON BIENVENIDOS. 
## Att. Coordinación

**Comment by mrsranzart** [comment]
## ** VERSIÓN FINAL DE PORTAVASOS**
**Video demostrativo**
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/2p0JumxgsIk/0.jpg)](http://www.youtube.com/watch?v=2p0JumxgsIk)
![img_20170623_120904](https://user-images.githubusercontent.com/13109419/27498786-f751a984-5860-11e7-936d-43275022518b.jpg)

**Primera versión del portavasos**
![primerprototipo](https://user-images.githubusercontent.com/13109419/27498790-f9fc9978-5860-11e7-96a2-d3f0f8b124a8.jpg)
![img_20170615_185812](https://user-images.githubusercontent.com/13109419/27498791-fb466e12-5860-11e7-8355-dbbb0ffe03ba.jpg)
